### ISSUE TITLE
when the user send two reviews 

### ISSUE THREAD

**Issue by mohamad-alibrahim** [ghulamabbas2/shopit#3]
PUT:{{DOMIN}}/api/v1/review

{
    "success": false,
    "error": {
        "statusCode": 500
    },
    "errMessage": "Cannot read property 'toString' of undefined",
    "stack": "TypeError: Cannot read property 'toString' of undefined\n    at C:\\SHOPIT\\backend\\controllers\\productController.js:132:21\n    at CoreDocumentArray.find (<anonymous>)\n    at C:\\SHOPIT\\backend\\controllers\\productController.js:131:40\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}

**Comment by kcvdk3101** [comment]
@mohamad-alibrahim  check productController.js in backend
