### ISSUE TITLE
when you delete a Review

### ISSUE THREAD

**Issue by mohamad-alibrahim** [ghulamabbas2/shopit#4]
**Delete** {{DOMIN}}/api/v1/review?productId=60141c36afdfaa61a03e909e

{
    "success": false,
    "error": {
        "statusCode": 500
    },
    "errMessage": "Cannot read property 'toString' of undefined",
    "stack": "TypeError: Cannot read property 'toString' of undefined\n    at C:\\SHOPIT\\backend\\controllers\\productController.js:186:93\n    at CoreDocumentArray.filter (<anonymous>)\n    at CoreDocumentArray.filter (C:\\SHOPIT\\node_modules\\mongoose\\lib\\types\\core_array.js:856:30)\n    at C:\\SHOPIT\\backend\\controllers\\productController.js:186:37\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}

**Comment by kcvdk3101** [comment]
@mohamad-alibrahim  check productController.js in backend
